default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: result_analyzer_development
  host: localhost
  username: postgres
  password: Admin1234

test:
  <<: *default
  database: result_analyzer_test
  host: localhost
  username: postgres
  password: Admin1234

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>